local data = T {};
--[[
	We're not actually doing anything in game with the moon phase, but it does (apparently) affect results, so we might do something later? (Would like a nice moon graphic showing the phase if I ever manage to make it pretty...)
	The only real use for it at the moment is for log entries, for later statitstical analysis... which I doubt anybody is actually doing...
--]]
data.MoonPhasePercent = T {
	[1] = 100,
	[2] = 98,
	[3] = 95,
	[4] = 93,
	[5] = 90,
	[6] = 88,
	[7] = 86,
	[8] = 83,
	[9] = 81,
	[10] = 79,
	[11] = 76,
	[12] = 74,
	[13] = 71,
	[14] = 69,
	[15] = 67,
	[16] = 64,
	[17] = 62,
	[18] = 60,
	[19] = 57,
	[20] = 55,
	[21] = 52,
	[22] = 50,
	[23] = 48,
	[24] = 45,
	[25] = 43,
	[26] = 40,
	[27] = 38,
	[28] = 36,
	[29] = 33,
	[30] = 31,
	[31] = 29,
	[32] = 26,
	[33] = 24,
	[34] = 21,
	[35] = 19,
	[36] = 17,
	[37] = 14,
	[38] = 12,
	[39] = 10,
	[40] = 7,
	[41] = 5,
	[42] = 2,
	[43] = 0,
	[44] = 2,
	[45] = 5,
	[46] = 7,
	[47] = 10,
	[48] = 12,
	[49] = 14,
	[50] = 17,
	[51] = 19,
	[52] = 21,
	[53] = 24,
	[54] = 26,
	[55] = 29,
	[56] = 31,
	[57] = 33,
	[58] = 36,
	[59] = 38,
	[60] = 40,
	[61] = 43,
	[62] = 45,
	[63] = 48,
	[64] = 50,
	[65] = 52,
	[66] = 55,
	[67] = 57,
	[68] = 60,
	[69] = 62,
	[70] = 64,
	[71] = 67,
	[72] = 69,
	[73] = 71,
	[74] = 74,
	[75] = 76,
	[76] = 79,
	[77] = 81,
	[78] = 83,
	[79] = 86,
	[80] = 88,
	[81] = 90,
	[82] = 93,
	[83] = 95,
	[84] = 98
};

data.MoonPhase = T {
	[1] = 'Full Moon',
	[2] = 'Full Moon',
	[3] = 'Full Moon',
	[4] = 'Waning Gibbous',
	[5] = 'Waning Gibbous',
	[6] = 'Waning Gibbous',
	[7] = 'Waning Gibbous',
	[8] = 'Waning Gibbous',
	[9] = 'Waning Gibbous',
	[10] = 'Waning Gibbous',
	[11] = 'Waning Gibbous',
	[12] = 'Waning Gibbous',
	[13] = 'Waning Gibbous',
	[14] = 'Waning Gibbous',
	[15] = 'Waning Gibbous',
	[16] = 'Waning Gibbous',
	[17] = 'Waning Gibbous',
	[18] = 'Last Quarter',
	[19] = 'Last Quarter',
	[20] = 'Last Quarter',
	[21] = 'Last Quarter',
	[22] = 'Last Quarter',
	[23] = 'Last Quarter',
	[24] = 'Last Quarter',
	[25] = 'Last Quarter',
	[26] = 'Waning Crescent',
	[27] = 'Waning Crescent',
	[28] = 'Waning Crescent',
	[29] = 'Waning Crescent',
	[30] = 'Waning Crescent',
	[31] = 'Waning Crescent',
	[32] = 'Waning Crescent',
	[33] = 'Waning Crescent',
	[34] = 'Waning Crescent',
	[35] = 'Waning Crescent',
	[36] = 'Waning Crescent',
	[37] = 'Waning Crescent',
	[38] = 'Waning Crescent',
	[39] = 'New Moon',
	[40] = 'New Moon',
	[41] = 'New Moon',
	[42] = 'New Moon',
	[43] = 'New Moon',
	[44] = 'New Moon',
	[45] = 'New Moon',
	[46] = 'Waxing Crescent',
	[47] = 'Waxing Crescent',
	[48] = 'Waxing Crescent',
	[49] = 'Waxing Crescent',
	[50] = 'Waxing Crescent',
	[51] = 'Waxing Crescent',
	[52] = 'Waxing Crescent',
	[53] = 'Waxing Crescent',
	[54] = 'Waxing Crescent',
	[55] = 'Waxing Crescent',
	[56] = 'Waxing Crescent',
	[57] = 'Waxing Crescent',
	[58] = 'Waxing Crescent',
	[59] = 'First Quarter',
	[60] = 'First Quarter',
	[61] = 'First Quarter',
	[62] = 'First Quarter',
	[63] = 'First Quarter',
	[64] = 'First Quarter',
	[65] = 'First Quarter',
	[66] = 'First Quarter',
	[67] = 'Waxing Gibbous',
	[68] = 'Waxing Gibbous',
	[69] = 'Waxing Gibbous',
	[70] = 'Waxing Gibbous',
	[71] = 'Waxing Gibbous',
	[72] = 'Waxing Gibbous',
	[73] = 'Waxing Gibbous',
	[74] = 'Waxing Gibbous',
	[75] = 'Waxing Gibbous',
	[76] = 'Waxing Gibbous',
	[77] = 'Waxing Gibbous',
	[78] = 'Waxing Gibbous',
	[79] = 'Waxing Gibbous',
	[80] = 'Waxing Gibbous',
	[81] = 'Full Moon',
	[82] = 'Full Moon',
	[83] = 'Full Moon',
	[84] = 'Full Moon'
};

data.daysOfWeek = {
	-- Like moonphase, this is basically only going to be used for log files.
	[0] = 'Firesday',
	[1]	= 'Earthsday',
	[2]	= 'Watersday',
	[3] = 'Windsday',
	[4] = 'Iceday',
	[5] = 'Lightningday',
	[6] = 'Lightsday',
	[7] = 'Darksday',
};


data.hqGearTop = T {
	-- In-game item.Id for the HQ clamming tops that "Reduce clamming incidents". (Halves the chance of the 'something jumps in you bucket' incident, apparently).
	-- Mainly for reference, code will use :any(14457,14458,14459,14460,14461,14462,14463,14472).
	{ name = 'HUME_GILET_P1',                   id = 14457 },
	{ name = 'HUME_TOP_P1',                     id = 14458 },
	{ name = 'ELVAAN_GILET_P1',                 id = 14459 },
	{ name = 'ELVAAN_TOP_P1',                   id = 14460 },
	{ name = 'TARUTARU_MAILLOT_P1',             id = 14461 },
	{ name = 'TARUTARU_TOP_P1',                 id = 14472 },
	{ name = 'MITHRA_TOP_P1',                   id = 14462 },
	{ name = 'GALKA_GILET_P1',                  id = 14463 },
};
data.hqGearBottom = T {
	-- In-game item.Id for the HQ clamming bottoms that "Improve clamming results". (Apparently makes the higher value stuff slightly more common).
	-- Mainly for reference, code will use :any(15415,15416,15417,15418,15419,15420,15421,15424).
	{ name = 'HUME_TRUNKS_P1',                  id = 15415 },
	{ name = 'HUME_SHORTS_P1',                  id = 15416 },
	{ name = 'ELVAAN_TRUNKS_P1',                id = 15417 },
	{ name = 'ELVAAN_SHORTS_P1',                id = 15418 },
	{ name = 'TARUTARU_TRUNKS_P1',              id = 15419 },
	{ name = 'TARUTARU_SHORTS_P1',              id = 15424 },
	{ name = 'MITHRA_SHORTS_P1',                id = 15420 },
	{ name = 'GALKA_TRUNKS_P1',                 id = 15421 },
};
data.itemSlots = T {
	-- Equipment slots, for refrerence.
    [0] = {id=0,en="Main"},
    [1] = {id=1,en="Sub"},
    [2] = {id=2,en="Range"},
    [3] = {id=3,en="Ammo"},
    [4] = {id=4,en="Head"},
    [5] = {id=5,en="Body"},
    [6] = {id=6,en="Hands"},
    [7] = {id=7,en="Legs"},
    [8] = {id=8,en="Feet"},
    [9] = {id=9,en="Neck"},
    [10] = {id=10,en="Waist"},
    [11] = {id=11,en="Left Ear"},
    [12] = {id=12,en="Right Ear"},
    [13] = {id=13,en="Left Ring"},
    [14] = {id=14,en="Right Ring"},
    [15] = {id=15,en="Back"},
};
data.playerStatus = T {
	-- Probably won't ever use...
    [0] = {id=0,en="Idle"},
    [1] = {id=1,en="Engaged"},
    [2] = {id=2,en="Dead"},
    [3] = {id=3,en="Engaged dead"},
    [4] = {id=4,en="Event"},
    [5] = {id=5,en="Chocobo"},
    [8] = {id=8,en="Door Opening"},
    [9] = {id=9,en="Door Closing"},
    [10] = {id=10,en="Elevator Up"},
    [11] = {id=11,en="Elevator Down"},
    [33] = {id=33,en="Resting"},
    [34] = {id=34,en="Locked"},
    [38] = {id=38,en="Fishing fighting"},
    [39] = {id=39,en="Fishing caught"},
    [40] = {id=40,en="Fishing broken rod"},
    [41] = {id=41,en="Fishing broken line"},
    [42] = {id=42,en="Fishing caught monster"},
    [43] = {id=43,en="Fishing lost catch"},
    [44] = {id=44,en="Crafting"},
    [47] = {id=47,en="Sitting"},
    [48] = {id=48,en="Kneeling"},
    [50] = {id=50,en="Fishing"},
    [51] = {id=51,en="Fishing fighting center"},
    [52] = {id=52,en="Fishing fighting right"},
    [53] = {id=53,en="Fishing fighting left"},
    [56] = {id=56,en="Fishing rod in water"},
    [57] = {id=57,en="Fishing fish on hook"},
    [58] = {id=58,en="Fishing caught fish"},
    [59] = {id=59,en="Fishing rod break"},
    [60] = {id=60,en="Fishing line break"},
    [61] = {id=61,en="Fishing monster catch"},
    [62] = {id=62,en="Fishing no catch or lost"},
    [63] = {id=63,en="Sitchair 0"},
    [64] = {id=64,en="Sitchair 1"},
    [65] = {id=65,en="Sitchair 2"},
    [66] = {id=66,en="Sitchair 3"},
    [67] = {id=67,en="Sitchair 4"},
    [68] = {id=68,en="Sitchair 5"},
    [69] = {id=69,en="Sitchair 6"},
    [70] = {id=70,en="Sitchair 7"},
    [71] = {id=71,en="Sitchair 8"},
    [72] = {id=72,en="Sitchair 9"},
    [73] = {id=73,en="Sitchair 10"},
    [74] = {id=74,en="Sitchair 11"},
    [75] = {id=75,en="Sitchair 12"},
    [85] = {id=85,en="Mount"},
};
--[[
	Item Data starts here.
--]]
data.item_count = 35; -- For if we ever need to add more items to the list, we can update the count here, and not have to update for loops in a bunch of places...
data.item_list = T {
--[[
	ImGui expects data to be in tables for most Inputs it seems. It's stupid, but if you want to have something editable in the in-game configs, you have to set it as a table and just deal with it.
	Checkbox, InputInt, SliderFloat, etc.
	Things that would normally be in a table like, color information, are fine though as they.
	Things that are indirect - Radio, Combo etc - are also fine without the data being in a table.

		['key']		:	The games item log name, makes it easier to lookup the item. (item.LogNameSingular)
		name		:	Display name. (item.Name)
		id			:	Internal game item id. (item.Id)
		enabled		:	Is it being used? (Applies to Horizon)
		weight		:	The weight of this item in the bucket.
		vendor_low	:	How much this item sells for in vendors outside of a town / safe area. (Like the ones on the beach at Purgonorgo Island).
						Possibly 10% of what these vendors would charge you to buy the item.
		vendor_high	:	How much this item sells for in a town vendor where you have Lv 4+ fame. It seems to cap just before Lv 4 fame, I think based on the actual fame value rather than the level thresholds. (Levels of fame aren't the same fame value, like XP and job levels).
						It seems to always be either +2.5% or +10% on top of the vendor_low value, rounded down. Ashita doesn't have a way to see which it is for a specific item tho, so we can't just extract it from the resource manager.
		ah_value	:	How much is this item worth on the AH (approximately). Will never be perfectly accurate. My defaults are slightly under what was seen when I set them.
		use_ah		:	Should we use the ah_value when doing value / profit calculations for this item? Will fall back to vendor_[low/high] if it's 0.
		lifetime {
			seen				:	How many times this item has been dug up.
			seen_hq				:	Same, but when also wearing the HQ swimming bottoms that "Improve clamming results". Should never exceed seen, only possibly match it.
			gained				:	How many were actually gained from turning in buckets. Calculate lost by (seen - gained).
			one_bucket			:	Highest number seen in one bucket (upgraded or not)
			one_bucket_gained	:	Highest number actually gained from turning in a bucket.
			last_straw			:	Number of times this was the item that broke the bucket.
		}

--]]
	['bibiki urchin'] =							{ name = 'Bibiki Urchin',		id = 4318,		enabled = {true},	weight = {6},	vendor_low = {750},		vendor_high = {768},	ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['hobgoblin pie'] =							{ name = 'Hobgoblin Pie',		id = 4325,		enabled = {true},	weight = {6},	vendor_low = {150},		vendor_high = {165},	ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['loaf of hobgoblin bread'] =				{ name = 'Hobgoblin Bread',		id = 4328,		enabled = {true},	weight = {6},	vendor_low = {90},		vendor_high = {99},		ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['nebimonite'] =							{ name = 'Nebimonite',			id = 4361,		enabled = {true},	weight = {6},	vendor_low = {52},		vendor_high = {57},		ah_value = {300},		use_ah = {true},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['bunch of pamamas'] =						{ name = 'Pamamas',				id = 4468,		enabled = {false},	weight = {6},	vendor_low = {20},		vendor_high = {22},		ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['shall shell'] =							{ name = 'Shall Shell',			id = 4484,		enabled = {true},	weight = {6},	vendor_low = {300},		vendor_high = {307},	ah_value = {400},		use_ah = {true},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['bibiki slug'] =							{ name = 'Bibiki Slug',			id = 5122,		enabled = {true},	weight = {3},	vendor_low = {10},		vendor_high = {11},		ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['jacknife'] =								{ name = 'Jacknife',			id = 5123,		enabled = {true},	weight = {11},	vendor_low = {53},		vendor_high = {58},		ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['tropical clam'] =							{ name = 'Tropical Clam',		id = 5124,		enabled = {true},	weight = {20},	vendor_low = {5100},	vendor_high = {5227},	ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['vongola clam'] =							{ name = 'Vongola Clam',		id = 5131,		enabled = {true},	weight = {6},	vendor_low = {192},		vendor_high = {196},	ah_value = {400},		use_ah = {true},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['elshimo coconut'] =						{ name = 'Elshimo Coconut',		id = 5187,		enabled = {false},	weight = {6},	vendor_low = {43},		vendor_high = {47},		ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['pebble'] =								{ name = 'Pebble',				id = 17296,		enabled = {true},	weight = {7},	vendor_low = {1},		vendor_high = {1},		ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['broken willow fishing rod'] =				{ name = 'Bkn. Willow Rod',		id = 485,		enabled = {true},	weight = {6},	vendor_low = {0},		vendor_high = {0},		ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['suit of goblin mail'] =					{ name = 'Goblin Mail',			id = 507,		enabled = {true},	weight = {6},	vendor_low = {0},		vendor_high = {0},		ah_value = {1250},		use_ah = {true},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['suit of goblin armor'] =					{ name = 'Goblin Armor',		id = 510,		enabled = {true},	weight = {6},	vendor_low = {0},		vendor_high = {0},		ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['goblin mask'] =							{ name = 'Goblin Mask',			id = 511,		enabled = {true},	weight = {6},	vendor_low = {0},		vendor_high = {0},		ah_value = {300},		use_ah = {true},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['clump of pamtam kelp'] =					{ name = 'Pamtam Kelp',			id = 624,		enabled = {true},	weight = {6},	vendor_low = {8},		vendor_high = {8},		ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['elm log'] =								{ name = 'Elm Log',				id = 690,		enabled = {true},	weight = {6},	vendor_low = {384},		vendor_high = {393},	ah_value = {3000},		use_ah = {true},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['maple log'] =								{ name = 'Maple Log',			id = 691,		enabled = {true},	weight = {6},	vendor_low = {15},		vendor_high = {16},		ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['petrified log'] =							{ name = 'Petrified Log',		id = 703,		enabled = {true},	weight = {6},	vendor_low = {2150},	vendor_high = {2203},	ah_value = {2500},		use_ah = {true},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['handful of fish scales'] =				{ name = 'Fish Scales',			id = 864,		enabled = {true},	weight = {3},	vendor_low = {24},		vendor_high = {26},		ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['handful of pugil scales'] =				{ name = 'Pugil Scales',		id = 868,		enabled = {true},	weight = {3},	vendor_low = {24},		vendor_high = {26},		ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['crab shell'] =							{ name = 'Crab Shell',			id = 881,		enabled = {true},	weight = {6},	vendor_low = {383},		vendor_high = {392},	ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['turtle shell'] =							{ name = 'Turtle Shell',		id = 885,		enabled = {true},	weight = {6},	vendor_low = {1224},	vendor_high = {1254},	ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['coral fragment'] =						{ name = 'Coral Fragment',		id = 887,		enabled = {true},	weight = {6},	vendor_low = {1750},	vendor_high = {1793},	ah_value = {2000},		use_ah = {true},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['seashell'] =								{ name = 'Seashell',			id = 888,		enabled = {true},	weight = {6},	vendor_low = {30},		vendor_high = {33},		ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['chunk of rock salt'] =					{ name = 'Rock Salt',			id = 936,		enabled = {false},	weight = {6},	vendor_low = {4},		vendor_high = {4},		ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['high-quality crab shell'] =				{ name = 'H.Q. Crab Shell',		id = 1193,		enabled = {true},	weight = {6},	vendor_low = {3325},	vendor_high = {3408},	ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['piece of oxblood'] =						{ name = 'Oxblood',				id = 1311,		enabled = {true},	weight = {6},	vendor_low = {13250},	vendor_high = {13581},	ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['lacquer tree log'] =						{ name = 'Lacquer Tree Log',	id = 1446,		enabled = {true},	weight = {6},	vendor_low = {3500},	vendor_high = {3587},	ah_value = {5000},		use_ah = {true},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['titanictus shell'] =						{ name = 'Titanictus Shell',	id = 1586,		enabled = {true},	weight = {6},	vendor_low = {350},		vendor_high = {358},	ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['handful of high-quality pugil scales'] =	{ name = 'H.Q. Pugil Scls.',	id = 1587,		enabled = {true},	weight = {6},	vendor_low = {260},		vendor_high = {266},	ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['uragnite shell'] =						{ name = 'Uragnite Shell',		id = 1618,		enabled = {true},	weight = {6},	vendor_low = {1500},	vendor_high = {1537},	ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['igneous rock'] =							{ name = 'Igneous Rock',		id = 1654,		enabled = {false},	weight = {35},	vendor_low = {174},		vendor_high = {178},	ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
	['sack of white sand'] =					{ name = 'White Sand',			id = 1889,		enabled = {true},	weight = {7},	vendor_low = {258},		vendor_high = {264},	ah_value = {0},			use_ah = {false},	lifetime = T {	seen = 0,	seen_hq = 0,	gained = 0,		one_bucket = 0,		one_bucket_gained = 0,		last_straw = 0,} },
};

data.sorting = T { -- LUA sucks for arrays with odd keys, so lets make some cheat sheats for list sorting...
	alpha_asc = T { -- Alphabetical English Name
		[1] =	'bibiki slug',
		[2] =	'bibiki urchin',
		[3] =	'broken willow fishing rod',
		[4] =	'coral fragment',
		[5] =	'crab shell',
		[6] =	'elm log',
		[7] =	'elshimo coconut',
		[8] =	'handful of fish scales',
		[9] =	'suit of goblin armor',
		[10] =	'suit of goblin mail',
		[11] =	'goblin mask',
		[12] =	'high-quality crab shell',
		[13] =	'handful of high-quality pugil scales',
		[14] =	'loaf of hobgoblin bread',
		[15] =	'hobgoblin pie',
		[16] =	'igneous rock',
		[17] =	'jacknife',
		[18] =	'lacquer tree log',
		[19] =	'maple log',
		[20] =	'nebimonite',
		[21] =	'piece of oxblood',
		[22] =	'bunch of pamamas',
		[23] =	'clump of pamtam kelp',
		[24] =	'pebble',
		[25] =	'petrified log',
		[26] =	'handful of pugil scales',
		[27] =	'chunk of rock salt',
		[28] =	'seashell',
		[29] =	'shall shell',
		[30] =	'titanictus shell',
		[31] =	'tropical clam',
		[32] =	'turtle shell',
		[33] =	'uragnite shell',
		[34] =	'vongola clam',
		[35] =	'sack of white sand',
	},
	alpha_desc = T { -- Reverse Alphabetical English Name
		[1] = 'sack of white sand',
		[2] = 'vongola clam',
		[3] = 'uragnite shell',
		[4] = 'turtle shell',
		[5] = 'tropical clam',
		[6] = 'titanictus shell',
		[7] = 'shall shell',
		[8] = 'seashell',
		[9] = 'chunk of rock salt',
		[10] = 'handful of pugil scales',
		[11] = 'petrified log',
		[12] = 'pebble',
		[13] = 'clump of pamtam kelp',
		[14] = 'bunch of pamamas',
		[15] = 'piece of oxblood',
		[16] = 'nebimonite',
		[17] = 'maple log',
		[18] = 'lacquer tree log',
		[19] = 'jacknife',
		[20] = 'igneous rock',
		[21] = 'hobgoblin pie',
		[22] = 'loaf of hobgoblin bread',
		[23] = 'handful of high-quality pugil scales',
		[24] = 'high-quality crab shell',
		[25] = 'goblin mask',
		[26] = 'suit of goblin mail',
		[27] = 'suit of goblin armor',
		[28] = 'handful of fish scales',
		[29] = 'elshimo coconut',
		[30] = 'elm log',
		[31] = 'crab shell',
		[32] = 'coral fragment',
		[33] = 'broken willow fishing rod',
		[34] = 'bibiki urchin',
		[35] = 'bibiki slug',
	},
	weight_asc = T { -- Lowest to Highest Weight, then Alphabetical by English Name.
		[1] = 'bibiki slug',
		[2] = 'handful of fish scales',
		[3] = 'handful of pugil scales',
		[4] = 'bibiki urchin',
		[5] = 'broken willow fishing rod',
		[6] = 'coral fragment',
		[7] = 'crab shell',
		[8] = 'elm log',
		[9] = 'elshimo coconut',
		[10] = 'suit of goblin armor',
		[11] = 'suit of goblin mail',
		[12] = 'goblin mask',
		[13] = 'high-quality crab shell',
		[14] = 'handful of high-quality pugil scales',
		[15] = 'loaf of hobgoblin bread',
		[16] = 'hobgoblin pie',
		[17] = 'lacquer tree log',
		[18] = 'maple log',
		[19] = 'nebimonite',
		[20] = 'piece of oxblood',
		[21] = 'bunch of pamamas',
		[22] = 'clump of pamtam kelp',
		[23] = 'petrified log',
		[24] = 'chunk of rock salt',
		[25] = 'seashell',
		[26] = 'shall shell',
		[27] = 'titanictus shell',
		[28] = 'turtle shell',
		[29] = 'uragnite shell',
		[30] = 'vongola clam',
		[31] = 'pebble',
		[32] = 'sack of white sand',
		[33] = 'jacknife',
		[34] = 'tropical clam',
		[35] = 'igneous rock',
	},
	weight_desc = T { -- Highest to Lowest Weight, then Alphabetical by English Name.
		[1] = 'igneous rock',
		[2] = 'tropical clam',
		[3] = 'jacknife',
		[4] = 'pebble',
		[5] = 'sack of white sand',
		[6] = 'bibiki urchin',
		[7] = 'broken willow fishing rod',
		[8] = 'coral fragment',
		[9] = 'crab shell',
		[10] = 'elm log',
		[11] = 'elshimo coconut',
		[12] = 'suit of goblin armor',
		[13] = 'suit of goblin mail',
		[14] = 'goblin mask',
		[15] = 'high-quality crab shell',
		[16] = 'handful of high-quality pugil scales',
		[17] = 'loaf of hobgoblin bread',
		[18] = 'hobgoblin pie',
		[19] = 'lacquer tree log',
		[20] = 'maple log',
		[21] = 'nebimonite',
		[22] = 'piece of oxblood',
		[23] = 'bunch of pamamas',
		[24] = 'clump of pamtam kelp',
		[25] = 'petrified log',
		[26] = 'chunk of rock salt',
		[27] = 'seashell',
		[28] = 'shall shell',
		[29] = 'titanictus shell',
		[30] = 'turtle shell',
		[31] = 'uragnite shell',
		[32] = 'vongola clam',
		[33] = 'bibiki slug',
		[34] = 'handful of fish scales',
		[35] = 'handful of pugil scales',
	},
	vendor_asc = T { -- Lowest to Highest Vendor Value, then Alphabetical by English Name.
		[1] = 'broken willow fishing rod',
		[2] = 'suit of goblin armor',
		[3] = 'suit of goblin mail',
		[4] = 'goblin mask',
		[5] = 'pebble',
		[6] = 'chunk of rock salt',
		[7] = 'clump of pamtam kelp',
		[8] = 'bibiki slug',
		[9] = 'maple log',
		[10] = 'bunch of pamamas',
		[11] = 'handful of fish scales',
		[12] = 'handful of pugil scales',
		[13] = 'seashell',
		[14] = 'elshimo coconut',
		[15] = 'nebimonite',
		[16] = 'jacknife',
		[17] = 'loaf of hobgoblin bread',
		[18] = 'hobgoblin pie',
		[19] = 'igneous rock',
		[20] = 'vongola clam',
		[21] = 'sack of white sand',
		[22] = 'handful of high-quality pugil scales',
		[23] = 'shall shell',
		[24] = 'titanictus shell',
		[25] = 'crab shell',
		[26] = 'elm log',
		[27] = 'bibiki urchin',
		[28] = 'turtle shell',
		[29] = 'uragnite shell',
		[30] = 'coral fragment',
		[31] = 'petrified log',
		[32] = 'high-quality crab shell',
		[33] = 'lacquer tree log',
		[34] = 'tropical clam',
		[35] = 'piece of oxblood',
	},
	vendor_desc = T { -- Highest to Lowest Vendor Value, then Alphabetical by English Name.
		[1] = 'piece of oxblood',
		[2] = 'tropical clam',
		[3] = 'lacquer tree log',
		[4] = 'high-quality crab shell',
		[5] = 'petrified log',
		[6] = 'coral fragment',
		[7] = 'uragnite shell',
		[8] = 'turtle shell',
		[9] = 'bibiki urchin',
		[10] = 'elm log',
		[11] = 'crab shell',
		[12] = 'titanictus shell',
		[13] = 'shall shell',
		[14] = 'handful of high-quality pugil scales',
		[15] = 'sack of white sand',
		[16] = 'vongola clam',
		[17] = 'igneous rock',
		[18] = 'hobgoblin pie',
		[19] = 'loaf of hobgoblin bread',
		[20] = 'jacknife',
		[21] = 'nebimonite',
		[22] = 'elshimo coconut',
		[23] = 'seashell',
		[24] = 'handful of fish scales',
		[25] = 'handful of pugil scales',
		[26] = 'bunch of pamamas',
		[27] = 'maple log',
		[28] = 'bibiki slug',
		[29] = 'clump of pamtam kelp',
		[30] = 'chunk of rock salt',
		[31] = 'pebble',
		[32] = 'broken willow fishing rod',
		[33] = 'suit of goblin armor',
		[34] = 'suit of goblin mail',
		[35] = 'goblin mask',
	},
	autosort_order = T { -- Inventory order when auto-sorting. Games sorts (ASC) by item.ResourceId then item.Id. If it was just item.Id it would take from bibiki urchin to pebble, and push them to the bottom of the list.
		[1] = 'bibiki urchin',
		[2] = 'hobgoblin pie',
		[3] = 'loaf of hobgoblin bread',
		[4] = 'nebimonite',
		[5] = 'bunch of pamamas',
		[6] = 'shall shell',
		[7] = 'bibiki slug',
		[8] = 'jacknife',
		[9] = 'tropical clam',
		[10] = 'vongola clam',
		[11] = 'elshimo coconut',
		[12] = 'pebble',
		[13] = 'broken willow fishing rod',
		[14] = 'suit of goblin mail',
		[15] = 'suit of goblin armor',
		[16] = 'goblin mask',
		[17] = 'clump of pamtam kelp',
		[18] = 'elm log',
		[19] = 'maple log',
		[20] = 'petrified log',
		[21] = 'handful of fish scales',
		[22] = 'handful of pugil scales',
		[23] = 'crab shell',
		[24] = 'turtle shell',
		[25] = 'coral fragment',
		[26] = 'seashell',
		[27] = 'chunk of rock salt',
		[28] = 'high-quality crab shell',
		[29] = 'piece of oxblood',
		[30] = 'lacquer tree log',
		[31] = 'titanictus shell',
		[32] = 'handful of high-quality pugil scales',
		[33] = 'uragnite shell',
		[34] = 'igneous rock',
		[35] = 'sack of white sand',
	},
	redeem_order = T { -- The order the NPC gives them to you. Except the ones Horizon doesn't use, those I don't know so they're at the end.
		[1] = 'piece of oxblood',
		[2] = 'lacquer tree log',
		[3] = 'high-quality crab shell',
		[4] = 'uragnite shell',
		[5] = 'petrified log',
		[6] = 'elm log',
		[7] = 'bibiki urchin',
		[8] = 'coral fragment',
		[9] = 'turtle shell',
		[10] = 'handful of high-quality pugil scales',
		[11] = 'maple log',
		[12] = 'tropical clam',
		[13] = 'titanictus shell',
		[14] = 'broken willow fishing rod',
		[15] = 'goblin mask',
		[16] = 'suit of goblin mail',
		[17] = 'sack of white sand',
		[18] = 'suit of goblin armor',
		[19] = 'loaf of hobgoblin bread',
		[20] = 'crab shell',
		[21] = 'hobgoblin pie',
		[22] = 'nebimonite',
		[23] = 'seashell',
		[24] = 'handful of fish scales',
		[25] = 'handful of pugil scales',
		[26] = 'shall shell',
		[27] = 'vongola clam',
		[28] = 'clump of pamtam kelp',
		[29] = 'pebble',
		[30] = 'jacknife',
		[31] = 'bibiki slug',
		[32] = 'elshimo coconut',
		[33] = 'igneous rock',
		[34] = 'bunch of pamamas',
		[35] = 'chunk of rock salt',
	},
};

data.text_searches = T { -- Text matches to parse incoming text. Maybe one day it can be made to be multi-language? These are all converted to lowercase.
	-- An item was gained. Not used yet, could be used to verify bucket results. Returns 2 results, number and name, which could be the plural name.
	item_obtained			= "you obtain (%d+) (.*)!",
	-- A bucket was purchased. No results to check.
	clamming_new_bucket		= "obtained key item: clamming kit",
	-- An item was dug. Returns item log name, should only ever be singular, but we could make a cheat-sheet if it ever does...
	clamming_dig_item		= "you find a[n]? (.*) and toss it into your bucket.*", -- e.mode = 142
	-- The bucket was upgraded. Returns the new capacity.
	clamming_bucket_upgrade	= "your clamming capacity has increased to (%d+) ponzes!",
	-- The NPC told us how much weight is in the bucket. Returns the weight of the bucket's contents.
	clamming_weight_check	= "i'd say this bucket here weighs about (%d+) ponzes.",
	-- The NPC told us (Rudely!) that the bucket is empty. No results to check.
	clamming_empty_bucket	= "whaddaya think i am, stoopid. there ain't no clams in this here bucket! it don't weigh nuthin'!",
	-- The bucket was turned in - you get this whether it's broken, empty or full, no distinction at all. No results to check.
	clamming_bucket_turnin	= "you return the clamming kit", -- e.mode = 142
	-- Tells you the item you just dug broke the bucket. Comes as part of the item dug message. No results to check.
	clamming_overweight		= "but the weight is too much for the bucket and its bottom breaks.*",
	-- The bucket was broken in an 'incident' with the 200 capacity bucket. No results to check.
	clamming_incident		= "something jumps into your bucket and breaks through the bottom!",
	-- The NPC offers a bucket. Useful for verifying we don't have one already, and copnfirming the bucket price. Returns the bucket price, which shouldn't ever actually change...
	clamming_no_bucket		= "it'll only cost ya a mere (%d+) gil!", -- e.mode = 150
	-- If the message starts with this, it came from the NPC... probably. Also, probably won't ever use it, since we're already checking the e.mode on the incoming text. No results to check.
	clamming_toh_zonikki	= "toh zonikki :",
	-- These 2 are what you might get when you click on a clamming point. We only want to check for these as a way of seeing if we need to refresh the display timer.
	-- But why bother checking this one? Sometimes you go away while at the clamming point, and the display times out, so this refreshes it when you first hit the point so you can see where you left off.
	clamming_dig_point_1	= "it looks like someone has been digging here.", -- e.mode = 142
	clamming_dig_point_2	= "the area is littered with pieces of broken seashells.", -- e.mode = 151.
};

data.sorting_scratch = T { -- Semi-Cheat array for some custom sorting... (Needs work, but better than the cheat-sheets if it ends up viable).
--[[
	id		:	The games internal id. (item.Id)
	key		:	The key used for this item in the main data array up above. We're using the games log file name (item.LogNameSingular) to make things a bit simpler elsewhere.
	name	:	The games display name. (item.Name)
				Used for sorting alphabetically, and secondary sort for the other options.
	name_jp	:	The games JP text for this item - it doesn't have different text for log display in JP so this counts as item.Name, item.LogNameSingular and item.LogNamePlural for parsing JP text as far as I can tell. We don't actually use it right now...
	weight	:	The weight of this item in the bucket.
				Used for sorting by weight.
	vendor	:	The value this item sells for at the bibiki bay mechants.
				Used for sorting by vendor value.
	inv		:	Pre-calculated numeric sequence for how the item is sorted in player inventory. The game sorts it by ascending item.ResourceId, then ascending item.Id.
	gain	:	Pre-calculated numeric sequence for how the NPC gives you the items when you turn in the bucket. No rhym or reason I can see. Horizon disabled items set as the last items in alphabetical order.
	seen	:	Populate this with the item stats (item_list.lifetime.seen) to sort by rarity.
	breaks	:	Populate this with the item stats (item_list.lifetime.last_straw) to sort by "danger".
	value	:	Populate this with AH value (item_list.ah_value) for custom value sorting.
				Alternately: populate with total value (ie, also multiply it by 'seen') for total value sorting.
]]--
	[1]	=	{ id = 4318,	key = 'bibiki urchin',							name = 'Bibiki Urchin',		name_jp = 'ビビキーアーチン',		weight = 6,		vendor = 750,	inv = 1,	gain = 7,	seen = 0,	breaks = 0,	value = 750 },
	[2] =	{ id = 4325,	key = 'hobgoblin pie',							name = 'Hobgoblin Pie',		name_jp = 'ホブゴブリンパイ',		weight = 6,		vendor = 150,	inv = 2,	gain = 21,	seen = 0,	breaks = 0,	value = 150 },
	[3] =	{ id = 4328,	key = 'loaf of hobgoblin bread',				name = 'Hobgoblin Bread',	name_jp = 'ホブゴブリンパン',		weight = 6,		vendor = 90,	inv = 3,	gain = 19,	seen = 0,	breaks = 0,	value = 90 },
	[4] =	{ id = 4361,	key = 'nebimonite',								name = 'Nebimonite',		name_jp = 'ネビムナイト',		weight = 6,		vendor = 52,	inv = 4,	gain = 22,	seen = 0,	breaks = 0,	value = 52 },
	[5] =	{ id = 4468,	key = 'bunch of pamamas',						name = 'Pamamas',			name_jp = 'パママ',			weight = 6,		vendor = 20,	inv = 5,	gain = 34,	seen = 0,	breaks = 0,	value = 20 },
	[6] =	{ id = 4484,	key = 'shall shell',							name = 'Shall Shell',		name_jp = 'シャル貝',			weight = 6,		vendor = 300,	inv = 6,	gain = 26,	seen = 0,	breaks = 0,	value = 300 },
	[7] =	{ id = 5122,	key = 'bibiki slug',							name = 'Bibiki Slug',		name_jp = 'ビビキースラッグ',		weight = 3,		vendor = 10,	inv = 7,	gain = 31,	seen = 0,	breaks = 0,	value = 10 },
	[8] =	{ id = 5123,	key = 'jacknife',								name = 'Jacknife',			name_jp = 'ジャックナイフ',		weight = 11,	vendor = 53,	inv = 8,	gain = 30,	seen = 0,	breaks = 0,	value = 53 },
	[9] =	{ id = 5124,	key = 'tropical clam',							name = 'Tropical Clam',		name_jp = 'トロピカルクラム',		weight = 20,	vendor = 5100,	inv = 9,	gain = 12,	seen = 0,	breaks = 0,	value = 5100 },
	[10] =	{ id = 5131,	key = 'vongola clam',							name = 'Vongola Clam',		name_jp = 'ボンゴラ',			weight = 6,		vendor = 192,	inv = 10,	gain = 27,	seen = 0,	breaks = 0,	value = 192 },
	[11] =	{ id = 5187,	key = 'elshimo coconut',						name = 'Elshimo Coconut',	name_jp = 'エルシモパームの実',	weight = 6,		vendor = 43,	inv = 11,	gain = 32,	seen = 0,	breaks = 0,	value = 43 },
	[12] =	{ id = 17296,	key = 'pebble',									name = 'Pebble',			name_jp = '石つぶて',			weight = 7,		vendor = 1,		inv = 12,	gain = 29,	seen = 0,	breaks = 0,	value = 1 },
	[13] =	{ id = 485,		key = 'broken willow fishing rod',				name = 'Bkn. Willow Rod',	name_jp = '折れたヤナギの釣竿',	weight = 6,		vendor = 0,		inv = 13,	gain = 14,	seen = 0,	breaks = 0,	value = 0 },
	[14] =	{ id = 507,		key = 'suit of goblin mail',					name = 'Goblin Mail',		name_jp = 'ゴブリンメイル',		weight = 6,		vendor = 0,		inv = 14,	gain = 16,	seen = 0,	breaks = 0,	value = 0 },
	[15] =	{ id = 510,		key = 'suit of goblin armor',					name = 'Goblin Armor',		name_jp = 'ゴブリンアーマー',		weight = 6,		vendor = 0,		inv = 15,	gain = 18,	seen = 0,	breaks = 0,	value = 0 },
	[16] =	{ id = 511,		key = 'goblin mask',							name = 'Goblin Mask',		name_jp = 'ゴブリンマスク',		weight = 6,		vendor = 0,		inv = 16,	gain = 15,	seen = 0,	breaks = 0,	value = 0 },
	[17] =	{ id = 624,		key = 'clump of pamtam kelp',					name = 'Pamtam Kelp',		name_jp = 'パムタム海苔',		weight = 6,		vendor = 8,		inv = 17,	gain = 28,	seen = 0,	breaks = 0,	value = 8 },
	[18] =	{ id = 690,		key = 'elm log',								name = 'Elm Log',			name_jp = 'エルム原木',		weight = 6,		vendor = 384,	inv = 18,	gain = 6,	seen = 0,	breaks = 0,	value = 384 },
	[19] =	{ id = 691,		key = 'maple log',								name = 'Maple Log',			name_jp = 'メープル原木',		weight = 6,		vendor = 15,	inv = 19,	gain = 11,	seen = 0,	breaks = 0,	value = 15 },
	[20] =	{ id = 703,		key = 'petrified log',							name = 'Petrified Log',		name_jp = '埋れ木',			weight = 6,		vendor = 2150,	inv = 20,	gain = 5,	seen = 0,	breaks = 0,	value = 2150 },
	[21] =	{ id = 864,		key = 'handful of fish scales',					name = 'Fish Scales',		name_jp = '魚の鱗',			weight = 3,		vendor = 24,	inv = 21,	gain = 24,	seen = 0,	breaks = 0,	value = 24 },
	[22] =	{ id = 868,		key = 'handful of pugil scales',				name = 'Pugil Scales',		name_jp = '陸魚の鱗',			weight = 3,		vendor = 24,	inv = 22,	gain = 25,	seen = 0,	breaks = 0,	value = 24 },
	[23] =	{ id = 881,		key = 'crab shell',								name = 'Crab Shell',		name_jp = '陸ガニの甲殻',		weight = 6,		vendor = 383,	inv = 23,	gain = 20,	seen = 0,	breaks = 0,	value = 383 },
	[24] =	{ id = 885,		key = 'turtle shell',							name = 'Turtle Shell',		name_jp = '海亀の甲羅',		weight = 6,		vendor = 1224,	inv = 24,	gain = 9,	seen = 0,	breaks = 0,	value = 1224 },
	[25] =	{ id = 887,		key = 'coral fragment',							name = 'Coral Fragment',	name_jp = '珊瑚のかけら',		weight = 6,		vendor = 1750,	inv = 25,	gain = 8,	seen = 0,	breaks = 0,	value = 1750 },
	[26] =	{ id = 888,		key = 'seashell',								name = 'Seashell',			name_jp = '貝殻',			weight = 6,		vendor = 30,	inv = 26,	gain = 23,	seen = 0,	breaks = 0,	value = 30 },
	[27] =	{ id = 936,		key = 'chunk of rock salt',						name = 'Rock Salt',			name_jp = '岩塩',			weight = 6,		vendor = 4,		inv = 27,	gain = 35,	seen = 0,	breaks = 0,	value = 4 },
	[28] =	{ id = 1193,	key = 'high-quality crab shell',				name = 'H.Q. Crab Shell',	name_jp = '上質な陸ガニの甲殻',	weight = 6,		vendor = 3325,	inv = 28,	gain = 3,	seen = 0,	breaks = 0,	value = 3325 },
	[29] =	{ id = 1311,	key = 'piece of oxblood',						name = 'Oxblood',			name_jp = 'オックスブラッド',		weight = 6,		vendor = 13250,	inv = 29,	gain = 1,	seen = 0,	breaks = 0,	value = 13250 },
	[30] =	{ id = 1446,	key = 'lacquer tree log',						name = 'Lacquer Tree Log',	name_jp = 'ラッカー原木',		weight = 6,		vendor = 3500,	inv = 30,	gain = 2,	seen = 0,	breaks = 0,	value = 3500 },
	[31] =	{ id = 1586,	key = 'titanictus shell',						name = 'Titanictus Shell',	name_jp = '甲冑魚の甲殻',		weight = 6,		vendor = 350,	inv = 31,	gain = 13,	seen = 0,	breaks = 0,	value = 350 },
	[32] =	{ id = 1587,	key = 'handful of high-quality pugil scales',	name = 'H.Q. Pugil Scls.',	name_jp = '上質な魚の鱗',		weight = 6,		vendor = 260,	inv = 32,	gain = 10,	seen = 0,	breaks = 0,	value = 260 },
	[33] =	{ id = 1618,	key = 'uragnite shell',							name = 'Uragnite Shell',	name_jp = 'ウラグナイトの殻',		weight = 6,		vendor = 1500,	inv = 33,	gain = 4,	seen = 0,	breaks = 0,	value = 1500 },
	[34] =	{ id = 1654,	key = 'igneous rock',							name = 'Igneous Rock',		name_jp = '火成岩',			weight = 35,	vendor = 174,	inv = 34,	gain = 33,	seen = 0,	breaks = 0,	value = 174 },
	[35] =	{ id = 1889,	key = 'sack of white sand',						name = 'White Sand',		name_jp = '白砂',			weight = 7,		vendor = 258,	inv = 35,	gain = 17,	seen = 0,	breaks = 0,	value = 258 },
};

return data;
